### ISSUE TITLE
Compatibility with the Group Tools Plugin

### ISSUE THREAD

**Issue by Pasley70** [nlybe/Elgg-Groupsmap#2]
If the Group Tools Plugin is active, on the Group-Invite-Page the "Map of Groups"-Tab is also shown.

Purpose for fix:

see /lib/hooks.php
line 24

extend

`if(strpos($item->getName(),'tools')!==false) {`

with

`if(strpos($item->getName(),'tools')!==false || strpos($item->getHref(),'tools')!==false) {`

**Comment by nlybe** [comment]
This is not real issue. The "Map of Groups" tab can be disable in plugin settings, no matter if group_tools is enabled or not
